server:
  servlet:
    context-path: /api
  shutdown: graceful
  port: 8080

spring:
  application:
    name: user-auth-service
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_batch_fetch_size: 1000
    show-sql: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: db_user
    password: password
    hikari:
      maximum-pool-size: 30
      minimum-idle: 30
  flyway:
    enabled: true
    locations: classpath:db/migration

snowflake:
  worker-id: 1

cors:
  allowed-origins:
    - http://localhost:8080
  allowed-origin-patterns:
    - http://localhost:*
  allowed-methods:
    - GET
    - POST
    - PUT
    - DELETE
    - PATCH
    - OPTIONS
  allowed-headers:
    - "*"
  allow-credentials: true
  max-age: 3600

jwt:
  secret: jwt-secret-key-change-this-in-production
  access-token-expiration: 900000 # 15 minutes in milliseconds
  refresh-token-expiration: 604800000 # 7 days in milliseconds
  issuer: user-auth-service
